# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_edge_list <- function(seqs, thresh = 2.0, v_gene = NULL, j_gene = NULL, match_v = FALSE, match_j = FALSE, ids = NULL) {
    .Call('_immApex_fast_edge_list', PACKAGE = 'immApex', seqs, thresh, v_gene, j_gene, match_v, match_j, ids)
}

