# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateMotif_cpp <- function(sequences, motif_lengths, discontinuous = FALSE, gap_char = '.', nthreads_requested = 1L) {
    .Call(`_immApex_calculateMotif_cpp`, sequences, motif_lengths, discontinuous, gap_char, nthreads_requested)
}

encodeSequences_cpp <- function(sequences, mode = "onehot", alphabet = as.character( c("A","C","D","E","F","G","H","I","K","L","M","N","P","Q","R","S","T","V","W","Y")), prop_mat_ = NULL, pad_token = '.', summary = "", max_len = -1L, nthreads = 1L) {
    .Call(`_immApex_encodeSequences_cpp`, sequences, mode, alphabet, prop_mat_, pad_token, summary, max_len, nthreads)
}

fast_edge_list <- function(seqs, thresh = 1.0, v_gene = NULL, j_gene = NULL, match_v = FALSE, match_j = FALSE, ids = NULL) {
    .Call(`_immApex_fast_edge_list`, seqs, thresh, v_gene, j_gene, match_v, match_j, ids)
}

